In [196]:
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.core.operations import SymmOp
import numpy as np

In [204]:
with MPRester("g23npTJNAhDPnQMr") as m:

    # Structure and doc for material id
    struct = m.get_structure_by_material_id("mp-9363")

#  1. Position des atomes dans le cristal

In [205]:
Rb = [0.00000000,0.00000000,0.00000000]
Nd = [0.50000000,0.50000000,0.50000000]
S1 = [0.23241300,0.23241300,0.23241300]
S2 = [0.76758700,0.76758700,0.76758700]

# 2. Symétries

## 2.1 Inversion

In [214]:
s1 = SymmOp.from_xyz_string('-x,-y,-z')
op1 = s1.operate(Nd)
rot1 = s1.rotation_matrix
print("Matrice de rotation :\n",rot1)
print(" ")
print("Position initial de l'atome de Néodyme :",Nd)
print("Position de l'atome de Néodyme après l'inversion:",op1)

#Affiche du cristal
view = quick_view(struct,conventional=True)
display(view)
view.script("draw symop 2 {atomno = 2}")

Matrice de rotation :
 [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
 
Position initial de l'atome de Néodyme : [0.5, 0.5, 0.5]
Position de l'atome de Néodyme après l'inversion: [-0.5 -0.5 -0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 2.2 Réflexion

In [207]:
s2 = SymmOp.from_xyz_string('-y,-x,z')
op2 = s2.operate(S1)
rot2 = s2.rotation_matrix
print("Matrice de rotation :\n",rot2)
print("Le déterminant de la matrice vaut {}, on a donc bien une opération de rotation".format(np.linalg.det(rot2)))
print(" ")
print("Position initial de l'atome de Souffre :",S1)
print("Position de l'atome de Souffre après la réflexion:",op2)

#Affichage du cristal
view2 = quick_view(struct,conventional=True)
display(view2)
view2.script("draw symop 8 {atomno = 3}")

Matrice de rotation :
 [[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Le déterminant de la matrice vaut -1.0, on a donc bien une opération de rotation
 
Position initial de l'atome de Souffre : [0.232413, 0.232413, 0.232413]
Position de l'atome de Souffre après la réflexion: [-0.232413 -0.232413  0.232413]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 2.3 Rotation d'ordre 3

In [216]:
s3 = SymmOp.from_xyz_string('-y, x-y, z')
op3 = s3.operate(Rb)
rot3 = s3.rotation_matrix
print("Matrice de rotation :\n",rot3)
print("Le déterminant de la matrice vaut {}, on a donc bien une opération de rotation".format(np.linalg.det(rot3)))
print("C'est une rotation d'ordre 3 car la rotation est de 120°")
print(" ")
print("Position initial de l'atome de Rubidium :",Rb)
print("Position de l'atome de Rubidium après la réflexion:",op3)


#Affichage du cristal
view3 = quick_view(struct,conventional=True)
display(view3)
view3.script("draw SYMOP 3 {atomno = 4}")



Matrice de rotation :
 [[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
Le déterminant de la matrice vaut 1.0, on a donc bien une opération de rotation
C'est une rotation d'ordre 3 car la rotation est de 120°
 
Position initial de l'atome de Rubidium : [0.0, 0.0, 0.0]
Position de l'atome de Rubidium après la réflexion: [0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))